name: ContextCoderEnv
channels:
  - defaults
dependencies:
  - aiohttp=3.8.5
  - aiosignal=1.3.1
  - altair=5.1.1
  - anyio=4.0.0
  - appdirs=1.4.4
  - asttokens=2.4.0
  - async-timeout=4.0.3
  - atomicwrites=1.4.1
  - attrs=23.1.0
  - aws-c-auth=0.7.3
  - aws-c-cal=0.6.2
  - aws-c-common=0.9.0
  - aws-c-compression=0.2.17
  - aws-c-event-stream=0.3.2
  - aws-c-http=0.7.12
  - aws-c-io=0.13.32
  - aws-c-mqtt=0.9.6
  - aws-c-s3=0.3.17
  - aws-c-sdkutils=0.1.12
  - aws-checksums=0.1.17
  - aws-crt-cpp=0.23.1
  - aws-sdk-cpp=1.11.156
  - backcall=0.2.0
  - backoff=1.11.1
  - backports=1.0
  - backports.functools_lru_cache=1.6.5
  - bcrypt=4.0.1
  - blinker=1.6.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.7.22
  - cachetools=5.3.1
  - certifi=2023.7.22
  - cffi=1.15.1
  - charset-normalizer=3.2.0
  - chroma-hnswlib=0.7.3
  - chromadb=0.4.12
  - click=8.1.7
  - colorama=0.4.6
  - coloredlogs=15.0.1
  - comm=0.1.4
  - contourpy=1.1.1
  - cryptography=41.0.4
  - cycler=0.11.0
  - dataclasses=0.8
  - dataclasses-json=0.5.7
  - debugpy=1.8.0
  - decorator=5.1.1
  - dlfcn-win32=1.3.0
  - docker-pycreds=0.4.0
  - et_xmlfile=1.1.0
  - exceptiongroup=1.1.3
  - executing=1.2.0
  - fastapi=0.99.1
  - fonttools=4.42.1
  - freetype=2.12.1
  - frozenlist=1.4.0
  - gitdb=4.0.10
  - gitpython=3.1.36
  - google-api-core=2.11.1
  - google-auth=2.23.0
  - googleapis-common-protos=1.60.0
  - greenlet=2.0.2
  - gtest=1.14.0
  - h11=0.14.0
  - humanfriendly=10.0
  - idna=3.4
  - importlib-metadata=6.8.0
  - importlib-resources=6.0.1
  - importlib_metadata=6.8.0
  - importlib_resources=6.0.1
  - intel-openmp=2023.2.0
  - ipykernel=6.25.2
  - ipython=8.15.0
  - ipywidgets=8.1.1
  - jedi=0.19.0
  - jinja2=3.1.2
  - joblib=1.3.2
  - js2py=0.74
  - jsonschema=4.19.1
  - jsonschema-specifications=2023.7.1
  - jupyter_client=8.3.1
  - jupyter_core=5.3.1
  - jupyterlab_widgets=3.0.9
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - langchain=0.0.293
  - langsmith=0.0.38
  - lark=1.1.7
  - lcms2=2.15
  - lerc=4.0.0
  - libabseil=20230802.1
  - libarrow=13.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.3.0
  - libdeflate=1.18
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgoogle-cloud=2.12.0
  - libgrpc=1.57.0
  - libhwloc=2.9.2
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - libpng=1.6.39
  - libprotobuf=4.23.4
  - libpulsar=3.2.0
  - libsodium=1.0.18
  - libsqlite=3.43.0
  - libssh2=1.11.0
  - libthrift=0.19.0
  - libtiff=4.5.1
  - libutf8proc=2.8.0
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.11.5
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markdown=3.4.4
  - markdown-it-py=3.0.0
  - markupsafe=2.1.3
  - marshmallow=3.20.1
  - marshmallow-enum=1.5.1
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.6
  - mdurl=0.1.0
  - mkl=2022.1.0
  - monotonic=1.5
  - mpmath=1.3.0
  - msys2-conda-epoch=20160418
  - multidict=6.0.4
  - munkres=1.1.4
  - mypy_extensions=1.0.0
  - nest-asyncio=1.5.6
  - numexpr=2.8.4
  - numpy=1.26.0
  - onnxruntime=1.15.1
  - openai=0.28.0
  - openapi-schema-pydantic=1.2.4
  - openjpeg=2.5.0
  - openpyxl=3.1.2
  - openssl=3.1.3
  - orc=1.9.0
  - overrides=7.4.0
  - packaging=23.1
  - pandas=2.1.1
  - pandas-stubs=2.0.3.230814
  - parso=0.8.3
  - pathtools=0.1.2
  - pickleshare=0.7.5
  - pillow=9.5.0
  - pip=23.2.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.10.0
  - plotly=5.17.0
  - posthog=3.0.2
  - prompt_toolkit=3.0.39
  - protobuf=4.23.4
  - psutil=5.9.5
  - pthread-stubs=0.4
  - pthreads-win32=2.9.1
  - pulsar-client=3.3.0
  - pure_eval=0.2.2
  - pyarrow=13.0.0
  - pyasn1=0.5.0
  - pyasn1-modules=0.3.0
  - pycparser=2.21
  - pydantic=1.10.12
  - pydeck=0.8.0
  - pygments=2.16.1
  - pyjsparser=2.7.1
  - pympler=1.0.1
  - pyopenssl=23.2.0
  - pyparsing=3.1.1
  - pypdf=3.16.2
  - pypika=0.48.9
  - pyreadline3=3.4.1
  - pysocks=1.7.1
  - python=3.11.5
  - python-dateutil=2.8.2
  - python-dotenv=1.0.0
  - python-flatbuffers=23.5.26
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytz=2023.3.post1
  - pyu2f=0.1.5
  - pywin32=304
  - pyyaml=6.0.1
  - pyzmq=25.1.1
  - re2=2023.03.02
  - referencing=0.30.2
  - regex=2023.8.8
  - requests=2.31.0
  - rich=13.5.3
  - rpds-py=0.10.3
  - rsa=4.9
  - scikit-learn=1.3.0
  - scipy=1.11.2
  - sentry-sdk=1.31.0
  - setproctitle=1.3.2
  - setuptools=68.2.2
  - shellingham=1.5.3
  - six=1.16.0
  - smmap=3.0.5
  - snappy=1.1.10
  - sniffio=1.3.0
  - sqlalchemy=2.0.21
  - stack_data=0.6.2
  - starlette=0.27.0
  - streamlit=1.27.0
  - stringcase=1.2.0
  - sympy=1.12
  - tbb=2021.10.0
  - tenacity=8.2.3
  - threadpoolctl=3.2.0
  - tiktoken=0.3.3
  - tk=8.6.12
  - tokenizers=0.13.3
  - toml=0.10.2
  - toolz=0.12.0
  - tornado=6.3.3
  - tqdm=4.66.1
  - traitlets=5.10.0
  - typer=0.9.0
  - types-pytz=2023.3.1.1
  - typing-extensions=4.8.0
  - typing_extensions=4.8.0
  - typing_inspect=0.9.0
  - typing_utils=0.1.0
  - tzdata=2023c
  - tzlocal=5.0.1
  - ucrt=10.0.22621.0
  - urllib3=1.26.15
  - uvicorn=0.23.2
  - validators=0.22.0
  - vc=14.3
  - vc14_runtime=14.36.32532
  - vs2015_runtime=14.36.32532
  - wandb=0.15.10
  - watchdog=3.0.0
  - wcwidth=0.2.6
  - wheel=0.41.2
  - widgetsnbextension
  - win_inet_pton=1.1.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.2
  - zeromq=4.3.4
  - zipp=3.17.0
  - zstd=1.5.5
  - pip:
      - beautifulsoup4==4.12.2
      - chardet==5.2.0
      - codeboxapi==0.0.15
      - codeinterpreterapi==0.0.10
      - emoji==2.8.0
      - filetype==1.2.0
      - google-search-results==2.4.2
      - lxml==4.9.3
      - nltk==3.8.1
      - python-iso639==2023.6.15
      - python-magic==0.4.27
      - soupsieve==2.5
      - tabulate==0.9.0
      - unstructured==0.10.16
      - websockets==11.0.3
